name: launch_counter
description: Flutter plugin that can show specific widgets based on the number of launches and the install time.
version: 1.0.0
repository: https://github.com/nosuke0926/launch_counter
issue_tracker: https://github.com/nosuke0926/launch_counter/issues

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
